[package]
name = "html"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.18" }

[dev-dependencies]
wasm-bindgen-test = "0.3"
web-sys = "0.3"
